version: "3"
services:
  nginx:
    image: carlcassar/nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/public
    networks:
      - carlcassar-network
  php:
    image: carlcassar/php
    volumes:
      - .:/var/www/html/public
    networks:
      - carlcassar-network
  memcached:
    image: memcached:alpine
    networks:
      - carlcassar-network
  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-app
      MYSQL_USER: app-user
      MYSQL_PASSWORD: app-pass
    volumes:
      - mariadbdata:/var/lib/mysql
    networks:
      - carlcassar-network
networks:
  carlcassar-network:
    driver: "bridge"
volumes:
  mariadbdata:
    driver: "local"
